version: '3.3'

services:
  database:
    container_name: task_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./local/db/data:/var/lib/mysql

  php:
    container_name: task_php
    build:
      context: .
    volumes:
      - ./src:/var/www
    ports:
      - '9000:9000'
    depends_on:
      - database

  nginx:
    container_name: task_nginx
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
